#!/bin/sh
while read file
do
        case "$1" in
        "C-w")
                echo "$file"
                set-wallpaper "$file" ;;
        esac
        case "$1" in
        "C-W")
                echo "$file"
                set-wallpaper "$file" -l ;;
        esac

done
